<?php
require_once '../config.php';
requireLogin('admin');

$conn = getDBConnection();

$sql = "SELECT 
            u.Username as AdmissionNumber, s.FirstName, s.LastName, 
            COUNT(asm.AssessmentID) as AssessmentsTaken,
            AVG(asm.Marks) as AverageMarks,
            MAX(asm.AssessmentDate) as LastAssessmentDate
        FROM assessment asm
        JOIN attachment a ON asm.AttachmentID = a.AttachmentID
        JOIN student s ON a.StudentID = s.StudentID
        JOIN users u ON s.UserID = u.UserID
        GROUP BY a.AttachmentID, u.Username, s.FirstName, s.LastName
        ORDER BY s.FirstName";
$result = $conn->query($sql);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Master Assessment Grades Report</title>
    <style>
        @page { size: A4 portrait; margin: 20mm; }
        body {
            font-family: 'Times New Roman', Times, serif;
            margin: 0; padding: 0; color: #000; background: #fff;
        }
        .container { width: 100%; max-width: 800px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
        .header img { height: 80px; margin-bottom: 10px; }
        .header h1 { margin: 0; font-size: 16pt; text-transform: uppercase; }
        .header h2 { margin: 5px 0 0 0; font-size: 14pt; text-transform: uppercase; }
        
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 10pt; }
        .data-table th, .data-table td { border: 1px solid #000; padding: 6px; text-align: left; }
        .data-table th { background-color: #f0f0f0; -webkit-print-color-adjust: exact; color-adjust: exact; }

        .print-btn {
            position: fixed; top: 20px; right: 20px;
            background: #8B1538; color: #fff; border: none;
            padding: 10px 20px; font-size: 14px; cursor: pointer; border-radius: 4px;
        }
        @media print { .print-btn { display: none; } }
    </style>
</head>
<body>
    <button class="print-btn" onclick="window.print()">Print / Save PDF</button>

    <div class="container">
        <div class="header">
            <img src="../assets/cuea-logo.png" alt="CUEA Logo">
            <h1>The Catholic University of Eastern Africa</h1>
            <h2>Master Assessment Grades Report</h2>
        </div>

        <div style="text-align: right; margin-bottom: 15px; font-size: 10pt;">
            <strong>Date Generated:</strong> <?php echo date('F j, Y'); ?>
        </div>

        <?php if ($result && $result->num_rows > 0): ?>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Student Name</th>
                        <th>Admission No.</th>
                        <th style="text-align: center;">Assessments Taken</th>
                        <th style="text-align: center;">Final Grade (Average %)</th>
                        <th>Last Assessment</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $totalScore = 0;
                    $count = 0;
                    while ($row = $result->fetch_assoc()): 
                        $totalScore += $row['AverageMarks'];
                        $count++;
                    ?>
                        <tr>
                            <td><?php echo htmlspecialchars($row['FirstName'] . ' ' . $row['LastName']); ?></td>
                            <td><?php echo htmlspecialchars($row['AdmissionNumber']); ?></td>
                            <td style="text-align: center;"><?php echo $row['AssessmentsTaken']; ?></td>
                            <td style="text-align: center; font-weight: bold;"><?php echo number_format($row['AverageMarks'], 1); ?></td>
                            <td style="white-space: nowrap;"><?php echo date('M d, Y', strtotime($row['LastAssessmentDate'])); ?></td>
                        </tr>
                    <?php endwhile; ?>
                </tbody>
            </table>
            
            <div style="font-size: 11pt; margin-top: 20px; display: flex; justify-content: space-between;">
                <div><strong>Total Graded Students:</strong> <?php echo $count; ?></div>
                <div><strong>Class Average Score:</strong> <?php echo $count > 0 ? number_format($totalScore / $count, 1) : 0; ?>%</div>
            </div>
            
        <?php else: ?>
            <p>No assessment records available.</p>
        <?php endif; ?>

        <div style="margin-top: 50px; font-size: 11pt;">
            <p><strong>Generated By:</strong> ___________________________ &nbsp;&nbsp;&nbsp;&nbsp; <strong>Signature:</strong> ___________________</p>
        </div>
    </div>
    
    <script>
        window.onload = function() { setTimeout(function() { window.print(); }, 500); };
    </script>
</body>
</html>
<?php $conn->close(); ?>
