<?php
require_once '../config.php';
requireLogin('admin');

$conn = getDBConnection();

$sql = "SELECT 
            u.Username as AdmissionNumber, s.FirstName, s.LastName, s.Course, 
            o.OrganizationName, a.AttachmentStatus, a.ClearanceStatus
        FROM attachment a
        JOIN student s ON a.StudentID = s.StudentID
        JOIN users u ON s.UserID = u.UserID
        LEFT JOIN hostorganization o ON a.HostOrgID = o.HostOrgID
        ORDER BY s.FirstName";
$result = $conn->query($sql);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Placement Completions Report</title>
    <style>
        @page { size: A4 portrait; margin: 20mm; }
        body {
            font-family: 'Times New Roman', Times, serif;
            margin: 0; padding: 0; color: #000; background: #fff;
        }
        .container { width: 100%; max-width: 800px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
        .header img { height: 80px; margin-bottom: 10px; }
        .header h1 { margin: 0; font-size: 16pt; text-transform: uppercase; }
        .header h2 { margin: 5px 0 0 0; font-size: 14pt; text-transform: uppercase; }
        .section-title { font-size: 12pt; font-weight: bold; margin-bottom: 10px; text-decoration: underline; }
        
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 10pt; }
        .data-table th, .data-table td { border: 1px solid #000; padding: 6px; text-align: left; }
        .data-table th { background-color: #f0f0f0; -webkit-print-color-adjust: exact; color-adjust: exact; }

        .print-btn {
            position: fixed; top: 20px; right: 20px;
            background: #8B1538; color: #fff; border: none;
            padding: 10px 20px; font-size: 14px; cursor: pointer; border-radius: 4px;
        }
        @media print { .print-btn { display: none; } }
    </style>
</head>
<body>
    <button class="print-btn" onclick="window.print()">Print / Save PDF</button>

    <div class="container">
        <div class="header">
            <img src="../assets/cuea-logo.png" alt="CUEA Logo">
            <h1>The Catholic University of Eastern Africa</h1>
            <h2>Student Placement Completions Report</h2>
        </div>

        <div style="text-align: right; margin-bottom: 15px; font-size: 10pt;">
            <strong>Date Generated:</strong> <?php echo date('F j, Y'); ?>
        </div>

        <?php if ($result && $result->num_rows > 0): ?>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Student Name</th>
                        <th>Admission No.</th>
                        <th>Course</th>
                        <th>Host Organization</th>
                        <th>Attachment Status</th>
                        <th>Clearance Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php while ($row = $result->fetch_assoc()): ?>
                        <tr>
                            <td><?php echo htmlspecialchars($row['FirstName'] . ' ' . $row['LastName']); ?></td>
                            <td><?php echo htmlspecialchars($row['AdmissionNumber']); ?></td>
                            <td><?php echo htmlspecialchars($row['Course']); ?></td>
                            <td><?php echo htmlspecialchars($row['OrganizationName'] ?: 'N/A'); ?></td>
                            <td><?php echo htmlspecialchars($row['AttachmentStatus']); ?></td>
                            <td><?php echo htmlspecialchars($row['ClearanceStatus'] ?? 'Pending'); ?></td>
                        </tr>
                    <?php endwhile; ?>
                </tbody>
            </table>
            
            <div style="font-size: 11pt; margin-top: 20px;">
                <strong>Total Records:</strong> <?php echo $result->num_rows; ?>
            </div>
            
        <?php else: ?>
            <p>No completion records available.</p>
        <?php endif; ?>

        <div style="margin-top: 50px; font-size: 11pt;">
            <p><strong>Generated By:</strong> ___________________________ &nbsp;&nbsp;&nbsp;&nbsp; <strong>Signature:</strong> ___________________</p>
        </div>
    </div>
    
    <script>
        window.onload = function() { setTimeout(function() { window.print(); }, 500); };
    </script>
</body>
</html>
<?php $conn->close(); ?>
