<?php
namespace App\Controllers;
use App\Core\Controller;
use App\Core\Helpers;

class AssessmentController extends Controller {

    public function index() {
        $this->requireAuth('staff');
        $staffModel = $this->model('Staff');
        
        $data = [
            'students' => $staffModel->getSupervisedStudents($_SESSION['LecturerID']),
            'title' => 'Assess Students',
            'page' => 'assessments',
            'page_css' => 'staff-dashboard.css'
        ];
        $this->view('staff/assessments', $data);
    }

    public function verifyCode() {
        $this->requireAuth('staff');

        // Admins do not conduct assessments
        if (isset($_SESSION['role']) && strtolower($_SESSION['role']) === 'admin') {
            $this->json(['success' => false, 'message' => 'Administrators do not conduct student assessments.']);
            return;
        }
        
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $this->verifyCsrf();
            $attachmentId = $_POST['attachment_id'];
            $enteredCode = Helpers::sanitize($_POST['assessment_code']);
            
            $assessmentModel = $this->model('Assessment');
            $actualCode = $assessmentModel->getAssessmentCode($attachmentId);
            
            if (!$actualCode) {
                $this->json(['success' => false, 'message' => 'Assessment code not generated by Host yet.']);
            } elseif (trim(strtoupper($enteredCode)) === trim(strtoupper($actualCode))) {
                $_SESSION['authorized_assessment_' . $attachmentId] = true;
                $this->json(['success' => true, 'redirect' => Helpers::baseUrl('/staff/assessment/conduct?attachment_id=' . $attachmentId)]);
            } else {
                $this->json(['success' => false, 'message' => 'Invalid Assessment Code.']);
            }
        }
    }

    public function conduct() {
        $this->requireAuth('staff');
        $attachmentId = $_GET['attachment_id'] ?? null;

        if (!$attachmentId || !isset($_SESSION['authorized_assessment_' . $attachmentId])) {
            header("Location: " . Helpers::baseUrl('/staff/assessments?error=unauthorized'));
            exit();
        }

        $assessmentModel = $this->model('Assessment');
        $scheduled = $assessmentModel->getScheduled($attachmentId);
        
        $data = [
            'attachment_id' => $attachmentId,
            'lecturer_id' => $_SESSION['LecturerID'],
            'scheduled' => $scheduled,
            'title' => 'Conduct Assessment',
            'page' => 'assessment',
            'page_css' => 'staff-dashboard.css'
        ];
        
        $this->view('staff/conduct-assessment', $data);
    }

    public function submit() {
        $this->requireAuth('staff');
        
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $this->verifyCsrf();
            $attachmentId = $_POST['attachment_id'];
            
            if (!isset($_SESSION['authorized_assessment_' . $attachmentId])) {
                header("Location: " . Helpers::baseUrl('/staff/assessments?error=unauthorized'));
                exit();
            }

            $assessmentModel = $this->model('Assessment');
            
            // Check for a scheduled assessment first
            $scheduled = $assessmentModel->getScheduled($attachmentId);
            
            $data = [
                'attachment_id' => $attachmentId,
                'lecturer_id' => $_SESSION['LecturerID'],
                'marks' => $_POST['total_score'],
                'remarks' => Helpers::sanitize($_POST['comments']),
                'criteria_scores' => json_encode($_POST['criteria'] ?? [])
            ];

            if ($scheduled) {
                // Update the scheduled assessment
                $result = $assessmentModel->update($scheduled['AssessmentID'], $data);
            } else {
                // Ad-hoc submission: create new
                $count = $assessmentModel->getAssessmentCount($attachmentId);
                $data['assessment_type'] = ($count == 0) ? 'First Assessment' : 'Final Assessment';
                $result = $assessmentModel->create($data);
            }

            if ($result) {
                unset($_SESSION['authorized_assessment_' . $attachmentId]);
                header("Location: " . Helpers::baseUrl('/staff/assessments?success=Assessment submitted'));
            } else {
                header("Location: " . Helpers::baseUrl('/staff/assessment/conduct?attachment_id=' . $attachmentId . '&error=db_error'));
            }
        }
    }
    // the function schedule() allows a staff member to schedule an assessment for a student's attachment by processing the form submission, 
    //validating the input, and inserting a new record into the assessment table with the provided details, including the attachment ID, lecturer ID, assessment type, date, and any remarks
    public function schedule() {
        $this->requireAuth('staff');

        // Admins do not conduct assessments
        if (isset($_SESSION['role']) && strtolower($_SESSION['role']) === 'admin') {
            $this->json(['success' => false, 'message' => 'Administrators do not schedule assessments.']);
            return;
        }

        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            if (empty($_POST['attachment_id']) || empty($_POST['assessment_date'])) {
                $this->json(['success' => false, 'message' => 'Missing required fields']);
                return;
            }

            $attachmentId = $_POST['attachment_id'];
            $assessmentModel = $this->model('Assessment');

            // Auto-determine type — system decides, not the lecturer
            $count = $assessmentModel->getAssessmentCount($attachmentId);
            $type = ($count == 0) ? 'First Assessment' : 'Final Assessment';

            $data = [
                'attachment_id' => $attachmentId,
                'lecturer_id'   => $_SESSION['LecturerID'],
                'assessment_type' => $type,
                'assessment_date' => $_POST['assessment_date'],
                'supervision_comments' => Helpers::sanitize($_POST['remarks'] ?? '')
            ];
            
            if ($assessmentModel->schedule($data)) {
                
                // Fetch details for email
                $db = (new \App\Config\Database())->connect();
                $stmt = $db->prepare("
                    SELECT s.Email as StudentEmail, s.FirstName, s.LastName,
                           h.Email as HostEmail, h.OrganizationName
                    FROM attachment a
                    JOIN student s ON a.StudentID = s.StudentID
                    JOIN hostorganization h ON a.HostOrgID = h.HostOrgID
                    WHERE a.AttachmentID = ?
                ");
                $stmt->bind_param("i", $attachmentId);
                $stmt->execute();
                $info = $stmt->get_result()->fetch_assoc();
                
                if ($info) {
                    $studentFullName = trim($info['FirstName'] . ' ' . $info['LastName']);
                    $dateFormatted = date('l, F j, Y', strtotime($_POST['assessment_date']));
                    
                    if (!empty($info['StudentEmail'])) {
                        \App\Core\Mailer::notifyAssessmentScheduled(
                            $info['StudentEmail'], 
                            $studentFullName, 
                            $studentFullName, 
                            $dateFormatted, 
                            $type
                        );
                    }
                    if (!empty($info['HostEmail'])) {
                        \App\Core\Mailer::notifyAssessmentScheduled(
                            $info['HostEmail'], 
                            $info['OrganizationName'], 
                            $studentFullName, 
                            $dateFormatted, 
                            $type
                        );
                    }
                }

                $this->json(['success' => true, 'message' => "$type scheduled successfully"]);
            } else {
                $this->json(['success' => false, 'message' => 'Failed to schedule assessment']);
            }
        }
    }


    public function viewAssessment() {
        // Allow student or staff/admin to view
        if (session_status() === PHP_SESSION_NONE) session_start();
        if (!isset($_SESSION['user_type'])) {
            header("Location: " . Helpers::baseUrl('/'));
            exit();
        }

        $assessmentId = $_GET['id'] ?? 0;
        $assessmentModel = $this->model('Assessment');
        $assessment = $assessmentModel->getById($assessmentId);

        if (!$assessment) { http_response_code(404); exit('Not found.'); }

        $userType = $_SESSION['user_type'];

        // Student: only own assessment
        if ($userType === 'student' && $assessment['StudentID'] != $_SESSION['student_id']) {
            http_response_code(403); exit('Unauthorized access.');
        }

        // Host org: only students attached to their organisation
        if ($userType === 'host_org') {
            $db = (new \App\Config\Database())->connect();
            $stmt = $db->prepare("SELECT 1 FROM attachment WHERE AttachmentID = ? AND HostOrgID = ? LIMIT 1");
            $stmt->bind_param("ii", $assessment['AttachmentID'], $_SESSION['host_org_id']);
            $stmt->execute();
            if ($stmt->get_result()->num_rows === 0) {
                http_response_code(403); exit('Unauthorized access.');
            }
        }

        // Staff: only supervised students
        if ($userType === 'staff') {
            $db = (new \App\Config\Database())->connect();
            $stmt = $db->prepare("SELECT 1 FROM supervision WHERE AttachmentID = ? AND LecturerID = ? LIMIT 1");
            $stmt->bind_param("ii", $assessment['AttachmentID'], $_SESSION['LecturerID']);
            $stmt->execute();
            if ($stmt->get_result()->num_rows === 0) {
                http_response_code(403); exit('Unauthorized access.');
            }
        }

        $data = ['assessment' => $assessment];
        $this->view('reports/print-assessment', $data, false);
    }
    // the function printSummary() allows authorized users (students, staff, or host organizations) to view a printable summary of a student's assessments 
    // by retrieving the relevant data and rendering it in a print-friendly format without the standard layout
    public function printSummary() {
        if (session_status() === PHP_SESSION_NONE) session_start();
        if (!isset($_SESSION['user_id'])) { header("Location: " . Helpers::baseUrl('/')); exit(); }

        $id = $_GET['id'] ?? ($_SESSION['user_type'] === 'student' ? $_SESSION['student_id'] : 0);
        $studentId = 0;

        $assessmentModel = $this->model('Assessment');
        $studentModel = $this->model('Student');

        // Check if $id is an AssessmentID by trying to fetch it
        $assessment = $assessmentModel->getById($id);
        if ($assessment) {
            $studentId = $assessment['StudentID'];
        } else {
            $studentId = $id;
        }

        $userType = $_SESSION['user_type'];

        // Student: only their own
        if ($userType === 'student' && $studentId != $_SESSION['student_id']) {
            http_response_code(403); exit('Unauthorized access.');
        }

        // Host org: only students attached to their org
        if ($userType === 'host_org') {
            $db = (new \App\Config\Database())->connect();
            $stmt = $db->prepare("SELECT 1 FROM attachment WHERE StudentID = ? AND HostOrgID = ? LIMIT 1");
            $stmt->bind_param("ii", $studentId, $_SESSION['host_org_id']);
            $stmt->execute();
            if ($stmt->get_result()->num_rows === 0) {
                http_response_code(403); exit('Unauthorized access.');
            }
        }

        // Staff: only supervised students
        if ($userType === 'staff') {
            $db = (new \App\Config\Database())->connect();
            $stmt = $db->prepare("SELECT 1 FROM supervision sup JOIN attachment a ON sup.AttachmentID = a.AttachmentID WHERE a.StudentID = ? AND sup.LecturerID = ? LIMIT 1");
            $stmt->bind_param("ii", $studentId, $_SESSION['LecturerID']);
            $stmt->execute();
            if ($stmt->get_result()->num_rows === 0) {
                http_response_code(403); exit('Unauthorized access.');
            }
        }

        $data = [
            'assessments' => $assessmentModel->getStudentAssessments($studentId), 
            'student' => $studentModel->getById($studentId)
        ];
        $this->view('reports/print-grades', $data, false);
    }
}
