<?php
namespace App\Controllers;
use App\Core\Controller;
use App\Core\Helpers;
// The AssessmentController manages all actions related to assessments, including scheduling, conducting, and viewing assessments for both staff and students. 
//It ensures that only authorized users can access specific functionalities and handles the logic for verifying assessment codes, submitting assessment results, and generating printable summaries of assessments.
class AssessmentController extends Controller {

    // --- Staff Actions ---
    
    public function index() {
        $this->requireAuth('staff');
        $staffModel = $this->model('Staff');
        
        $data = [
            'students' => $staffModel->getSupervisedStudents($_SESSION['LecturerID']),
            'title' => 'Assess Students',
            'page' => 'assessments',
            'page_css' => 'staff-dashboard.css'
        ];
        $this->view('staff/assessments', $data);
    }

    public function verifyCode() {
        $this->requireAuth('staff');
        
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $attachmentId = $_POST['attachment_id'];
            $enteredCode = Helpers::sanitize($_POST['assessment_code']);
            
            $assessmentModel = $this->model('Assessment');
            $actualCode = $assessmentModel->getAssessmentCode($attachmentId);
            
            if (!$actualCode) {
                $this->json(['success' => false, 'message' => 'Assessment code not generated by Host yet.']);
            } elseif (trim(strtoupper($enteredCode)) === trim(strtoupper($actualCode))) {
                $_SESSION['authorized_assessment_' . $attachmentId] = true;
                $this->json(['success' => true, 'redirect' => Helpers::baseUrl('/staff/assessment/conduct?attachment_id=' . $attachmentId)]);
            } else {
                $this->json(['success' => false, 'message' => 'Invalid Assessment Code.']);
            }
        }
    }

    public function conduct() {
        $this->requireAuth('staff');
        $attachmentId = $_GET['attachment_id'] ?? null;

        if (!$attachmentId || !isset($_SESSION['authorized_assessment_' . $attachmentId])) {
            header("Location: " . Helpers::baseUrl('/staff/assessments?error=unauthorized'));
            exit();
        }

        // Get student details for the form header (reusing Staff model logic or creating a specific method)
        // For simplicity, we'll pass the ID and let the view/model handle fetching details if needed, 
        // but ideally we fetch student name here.
        // Let's assume the view will display a generic form or we fetch basic info.
        
        $data = [
            'attachment_id' => $attachmentId,
            'lecturer_id' => $_SESSION['LecturerID'],
            'title' => 'Conduct Assessment',
            'page' => 'assessment',
            'page_css' => 'staff-dashboard.css'
        ];
        
        $this->view('staff/conduct-assessment', $data);
    }

    public function submit() {
        $this->requireAuth('staff');
        
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $attachmentId = $_POST['attachment_id'];
            
            if (!isset($_SESSION['authorized_assessment_' . $attachmentId])) {
                header("Location: " . Helpers::baseUrl('/staff/assessments?error=unauthorized'));
                exit();
            }

            $assessmentModel = $this->model('Assessment');
            $count = $assessmentModel->getAssessmentCount($attachmentId);
            $type = ($count == 0) ? 'First Assessment' : 'Final Assessment';

            $data = [
                'attachment_id' => $attachmentId,
                'lecturer_id' => $_SESSION['LecturerID'],
                'assessment_type' => $type,
                'marks' => $_POST['total_score'],
                'remarks' => Helpers::sanitize($_POST['comments']),
                'criteria_scores' => json_encode($_POST['criteria'] ?? [])
            ];

            if ($assessmentModel->create($data)) {
                unset($_SESSION['authorized_assessment_' . $attachmentId]);
                header("Location: " . Helpers::baseUrl('/staff/assessments?success=Assessment submitted'));
            } else {
                header("Location: " . Helpers::baseUrl('/staff/assessment/conduct?attachment_id=' . $attachmentId . '&error=db_error'));
            }
        }
    }
    // the function schedule() allows a staff member to schedule an assessment for a student's attachment by processing the form submission, 
    //validating the input, and inserting a new record into the assessment table with the provided details, including the attachment ID, lecturer ID, assessment type, date, and any remarks
    public function schedule() {
        $this->requireAuth('staff');
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            if (empty($_POST['attachment_id']) || empty($_POST['assessment_type']) || empty($_POST['assessment_date'])) {
                $this->json(['success' => false, 'message' => 'Missing required fields']);
                return;
            }

            $data = [
                'attachment_id' => $_POST['attachment_id'],
                'lecturer_id' => $_SESSION['LecturerID'],
                'assessment_type' => $_POST['assessment_type'],
                'assessment_date' => $_POST['assessment_date'],
                'remarks' => Helpers::sanitize($_POST['remarks'] ?? '')
            ];
            
            $assessmentModel = $this->model('Assessment');
            if ($assessmentModel->schedule($data)) {
                $this->json(['success' => true, 'message' => 'Assessment scheduled successfully']);
            } else {
                $this->json(['success' => false, 'message' => 'Failed to schedule assessment']);
            }
        }
    }

    // --- Student/Shared Actions ---

    public function viewAssessment() {
        // Allow student or staff/admin to view
        if (session_status() === PHP_SESSION_NONE) session_start();
        if (!isset($_SESSION['user_type'])) {
            header("Location: " . Helpers::baseUrl('/'));
            exit();
        }

        $assessmentId = $_GET['id'] ?? 0;
        $assessmentModel = $this->model('Assessment');
        $assessment = $assessmentModel->getById($assessmentId);

        // Security check: Student can only view their own
        if ($_SESSION['user_type'] === 'student' && $assessment['StudentID'] != $_SESSION['student_id']) {
            echo "Unauthorized access.";
            exit();
        }

        // Render the print view directly (no layout)
        $data = ['assessment' => $assessment];
        $this->view('reports/print-assessment', $data, false);
    }
    // the function printSummary() allows authorized users (students, staff, or host organizations) to view a printable summary of a student's assessments 
    // by retrieving the relevant data and rendering it in a print-friendly format without the standard layout
    public function printSummary() {
        if (session_status() === PHP_SESSION_NONE) session_start();
        if (!isset($_SESSION['user_id'])) { header("Location: " . Helpers::baseUrl('/')); exit(); }

        $studentId = $_GET['id'] ?? ($_SESSION['user_type'] === 'student' ? $_SESSION['student_id'] : 0);
        
        if ($_SESSION['user_type'] === 'student' && $studentId != $_SESSION['student_id']) {
            die("Unauthorized access.");
        }

        $assessmentModel = $this->model('Assessment');
        $studentModel = $this->model('Student');

        $data = ['assessments' => $assessmentModel->getStudentAssessments($studentId), 'student' => $studentModel->getById($studentId)];
        $this->view('reports/print-grades', $data, false);
    }
}
