<?php
namespace App\Models;
use App\Config\Database;
/**
 * Class Assessment
 * 
 * Manages database operations related to student assessments during their attachments.
 * Handles scheduling, creating, retrieving, and updating assessment records by academic supervisors.
 */
class Assessment {
    private $db;
    private $conn;

    /**
     * Initializes the database connection for assessment operations.
     */
    public function __construct() {
        $this->db = new Database();
        $this->conn = $this->db->connect();
    }

    /**
     * Retrieves the unique assessment verification code generated by a host organization
     * for a specific attachment. This code is required to authorize an assessment.
     * 
     * @param int $attachmentId The attachment ID
     * @return string|null The verification code, or null if not set
     */
    public function getAssessmentCode($attachmentId) {
        $stmt = $this->conn->prepare("SELECT AssessmentCode FROM attachment WHERE AttachmentID = ?");
        $stmt->bind_param("i", $attachmentId);
        $stmt->execute();
        $result = $stmt->get_result();
        if ($row = $result->fetch_assoc()) {
            return $row['AssessmentCode'];
        }
        return null;
    }

    /**
     * Calculates the total number of completed assessments for a specific attachment.
     * Useful for determining if a student is ready for a second assessment.
     * 
     * @param int $attachmentId The attachment ID
     * @return int Count of completed assessments
     */
    public function getAssessmentCount($attachmentId) {
        $stmt = $this->conn->prepare("SELECT COUNT(*) as count FROM assessment WHERE AttachmentID = ? AND Status = 'Completed'");
        $stmt->bind_param("i", $attachmentId);
        $stmt->execute();
        return $stmt->get_result()->fetch_assoc()['count'];
    }

    /**
     * Directly creates a new completed assessment record in the database.
     * Used for immediate assessments that were not previously scheduled.
     * 
     * @param array $data Associative array containing assessment details and scores
     * @return bool True on successful insert
     */
    public function create($data) {
        $sql = "INSERT INTO assessment (AttachmentID, LecturerID, AssessmentType, Marks, Remarks, AssessmentDate, CriteriaScores, Status)
                VALUES (?, ?, ?, ?, ?, CURDATE(), ?, 'Completed')";
        $stmt = $this->conn->prepare($sql);
        $stmt->bind_param("iisdss",
            $data['attachment_id'],
            $data['lecturer_id'],
            $data['assessment_type'],
            $data['marks'],
            $data['remarks'],
            $data['criteria_scores']
        );
        return $stmt->execute();
    }

    /**
     * Schedules a future assessment for a student.
     * Inserts a record with the status 'Scheduled' and placeholder marks.
     * 
     * @param array $data Details including scheduled date and supervision comments
     * @return bool True on successful scheduling
     */
    public function schedule($data) {
        // Now using SupervisionComments and Status columns.
        $sql = "INSERT INTO assessment (AttachmentID, LecturerID, AssessmentType, AssessmentDate, Marks, Status, SupervisionComments)
                VALUES (?, ?, ?, ?, 0, 'Scheduled', ?)";
        $stmt = $this->conn->prepare($sql);
        $stmt->bind_param("iisss",
            $data['attachment_id'],
            $data['lecturer_id'],
            $data['assessment_type'],
            $data['assessment_date'],
            $data['supervision_comments']
        );
        return $stmt->execute();
    }

    /**
     * Retrieves detailed information for a specific assessment record.
     * Includes joined data about the student, host organization, and assessor.
     * 
     * @param int $assessmentId
     * @return array|null Associative array of detailed assessment data
     */
    public function getById($assessmentId) {
        $sql = "SELECT
                    a.AssessmentDate, a.AssessmentType, a.Marks, a.Remarks, a.CriteriaScores, a.SupervisionComments, a.Status,
                    s.FirstName, s.LastName, u.Username as AdmissionNumber, s.Course, s.Faculty,
                    ho.OrganizationName,
                    l.Name as AssessorName, l.Department as AssessorDept,
                    att.StudentID
                FROM assessment a
                JOIN attachment att ON a.AttachmentID = att.AttachmentID
                JOIN student s ON att.StudentID = s.StudentID
                JOIN users u ON s.UserID = u.UserID
                JOIN hostorganization ho ON att.HostOrgID = ho.HostOrgID
                LEFT JOIN lecturer l ON a.LecturerID = l.LecturerID
                WHERE a.AssessmentID = ?";
        $stmt = $this->conn->prepare($sql);
        $stmt->bind_param("i", $assessmentId);
        $stmt->execute();
        return $stmt->get_result()->fetch_assoc();
    }

    /**
     * Retrieves a history of all assessments (both scheduled and completed) for a given student.
     * 
     * @param int $studentId
     * @return \mysqli_result|false Result set
     */
    public function getStudentAssessments($studentId) {
        $sql = "SELECT
                    a.AssessmentID, a.AssessmentDate, a.AssessmentType, a.Marks,
                    l.Name as AssessorName
                FROM assessment a
                JOIN attachment att ON a.AttachmentID = att.AttachmentID
                LEFT JOIN lecturer l ON a.LecturerID = l.LecturerID
                WHERE att.StudentID = ?
                ORDER BY a.AssessmentDate DESC";
        $stmt = $this->conn->prepare($sql);
        $stmt->bind_param("i", $studentId);
        $stmt->execute();
        return $stmt->get_result();
    }

    /**
     * Fetches a pending scheduled assessment for a specific attachment, if one exists.
     * 
     * @param int $attachmentId
     * @return array|null The scheduled assessment data, or null if none
     */
    public function getScheduled($attachmentId) {
        $stmt = $this->conn->prepare("SELECT * FROM assessment WHERE AttachmentID = ? AND Status = 'Scheduled' LIMIT 1");
        $stmt->bind_param("i", $attachmentId);
        $stmt->execute();
        return $stmt->get_result()->fetch_assoc();
    }

    /**
     * Updates an existing assessment record with scores and marks it as 'Completed'.
     * Used when fulfilling a previously scheduled assessment.
     * 
     * @param int $assessmentId The ID of the scheduled assessment
     * @param array $data The new scores and remarks
     * @return bool True on successful update
     */
    public function update($assessmentId, $data) {
        $sql = "UPDATE assessment SET 
                Marks = ?, 
                Remarks = ?, 
                CriteriaScores = ?, 
                Status = 'Completed', 
                AssessmentDate = CURDATE(),
                LecturerID = ?
                WHERE AssessmentID = ?";
        $stmt = $this->conn->prepare($sql);
        $stmt->bind_param("dssii", 
            $data['marks'], 
            $data['remarks'], 
            $data['criteria_scores'], 
            $data['lecturer_id'],
            $assessmentId
        );
        return $stmt->execute();
    }
}
